CREATE DATABASE lab_mysql;
USE lab_mysql;
CREATE TABLE Cars (
ID INT PRIMARY KEY AUTO_INCREMENT,
VIN VARCHAR (25) NOT NULL,
Manufacturer VARCHAR (15) NOT NULL,
Model VARCHAR (20) NOT NULL,
Year INT NOT NULL,
Color VARCHAR (8));

CREATE TABLE Customers (
ID INT PRIMARY KEY AUTO_INCREMENT,
Customer_ID INT NOT NULL,
Name VARCHAR (40) NOT NULL,
Phone VARCHAR (10) NOT NULL,
Email VARCHAR (30),
Address VARCHAR (40) NOT NULL,
City VARCHAR (25) NOT NULL,
State_or_Province VARCHAR (15) NOT NULL,
Country	VARCHAR (15) NOT NULL,
Postal INT NOT NULL);

CREATE TABLE Salespersons (
ID INT PRIMARY KEY AUTO_INCREMENT,
Staff_ID INT NOT NULL,
Name VARCHAR (40) NOT NULL,
Store VARCHAR (15) NOT NULL);

CREATE TABLE Invoices (
ID INT PRIMARY KEY AUTO_INCREMENT,
Invoice_Number INT NOT NULL,
Date DATE NOT NULL,
Car INT NOT NULL,
Customer INT NOT NULL,
Sale_Person INT NOT NULL);

ALTER TABLE Invoices
ADD FOREIGN KEY (Car)
REFERENCES Cars (ID);

ALTER TABLE Invoices
ADD FOREIGN KEY (Customer)
REFERENCES Customers (ID);

ALTER TABLE Invoices
ADD FOREIGN KEY (Sale_Person)
REFERENCES Salespersons (ID);